name = "HyperCubeTransform"
uuid = "9ec9aee3-0fd3-44c2-8e61-a50acc66f3c8"
authors = ["ptiede <ptiede91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MeasureTheory = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Tricks = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"

[compat]
Distributions = "0.24,0.25"
DocStringExtensions = "0.7,0.8"
GeneralizedGenerated = "0.3"
MLStyle = "0.4"
MeasureTheory = "0.10,0.11"
Requires = "1"
Tricks = "0.1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
